networks:
  web_network:
    external: true
  web_jacco_prod:

volumes:
  jacco_prod_app:

services:
  jacco_prod_app:
    build: .
    container_name: jacco_prod_app
    image: jacco_prod_app:latest
    command: gunicorn --bind 0.0.0.0:8000 jacco.wsgi:application
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - DJANGO_SETTINGS_MODULE=jacco.settings_prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "1000:1000"
    volumes:
#      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - jacco_prod_app_pgsql
    networks:
      - web_network
      - web_jacco_prod

  jacco_prod_app_pgsql:
    image: postgres:15
    container_name: jacco_prod_app_pgsql
    restart: always
    environment:
      POSTGRES_DB: jacco_db
      POSTGRES_USER: jacco_user
      POSTGRES_PASSWORD: jacco_pass
    volumes:
      - jacco_prod_app:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - web_jacco_prod

  jacco_prod_app_adminer:
    image: adminer
    container_name: jacco_prod_app_adminer
    restart: always
    ports:
      - "8087:8080"
    networks:
      - web_jacco_prod

